name: Publish Artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-maven:

    runs-on: ubuntu-latest
    env:
      MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MILL_PGP_SECRET_BASE64: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      MILL_PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Publish to Maven Central
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            ./mill -i mill.scalalib.SonatypeCentralPublishModule/ --bundleName "ammonite-${GITHUB_REF#refs/tags/v}"
          else
            ./mill -i mill.scalalib.SonatypeCentralPublishModule/
          fi
