name: Release (2)
on:
  push:
    branches:
      - main
      - 2.x
jobs:
  release2:
    runs-on: ubuntu-latest
    env:
      SONATYPE_PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
      SONATYPE_DEPLOY_USER: ${{ secrets.PUBLISH_USER }}
      SONATYPE_DEPLOY_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
      SONATYPE_PGP_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: test -z "$SONATYPE_PGP_SECRET" || echo "$SONATYPE_PGP_SECRET" | base64 --decode | gpg --import --no-tty --batch --yes
      - run: GPG_TTY=$(tty) ./mill -i publishSonatype __.publishArtifacts 2 5
