name: Run Tests
on:
  push:
    branches:
      - main
      - 2.x
  pull_request:

# cancel older runs of a pull request;
# this will not cancel anything for normal git pushes
concurrency:
  group: cancel-old-pr-runs-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      scala-matrix: ${{ steps.versions.outputs.scala-matrix }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: List Scala versions
        id: versions
        run: |
          matrix=$(./mill --silent show ciScalaVersions)
          {
            echo 'scala-matrix<<EOF'
            echo "$matrix"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  test:
    needs: versions
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.versions.outputs.scala-matrix) }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Test terminal
        if: matrix.test-terminal == 'true'
        run: ./mill -i -j1 -k 'terminal.__.test'
      - name: Test Scala ${{ matrix.scala-version }}
        run: |
          ./mill -i -j1 -k 'amm.repl[${{ matrix.binary-scala-version }}].test[${{ matrix.scala-version }}]'
          ./mill -i -j1 -k 'amm[${{ matrix.binary-scala-version }}].test[${{ matrix.scala-version }}]'

  itest:
    needs: versions
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.versions.outputs.scala-matrix) }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: ./mill -i -j1 -k 'integration[${{ matrix.scala-version }}].__.test'

  compileAll:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - run: ./mill -i -k -j1 '__.compile'
